#!/bin/bash
#
#   Copyright 2011 Carl Anderson
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#
# This file is intended to be common shell code for both zsh and bash.
#

# Make sure there is a command logger.
if [[ -z "${ASH_LOG_BIN}" ]]; then
  ASH_LOG_BIN=/usr/local/bin/_ash_log
fi
if ! [[ -x "${ASH_LOG_BIN}" ]]; then
  return
fi

# Create the directory holding the history database.
if [[ ! -e "${ASH_CFG_HISTORY_DB}" ]]; then
  mkdir -p "$( dirname "${ASH_CFG_HISTORY_DB}" )" \
    || ${ASH_LOG_BIN} -a "Failed to mkdir -p $( dirname "${ASH_CFG_HISTORY_DB}" )"
fi

# Ensure there is a HISTFILE.
if [[ -z "${HISTFILE}" ]]; then
  export HISTFILE="${ASH_CFG_HISTORY_DB%.db}"
  ${ASH_LOG_BIN} -a "WARN: HISTFILE undefined. Exporting HISTFILE as: '${HISTFILE}'."
fi
if [[ ! -e "${HISTFILE}" ]] && ! touch "${HISTFILE}" &>/dev/null; then
  ${ASH_LOG_BIN} -a "Failed to create shell history file: '${HISTFILE}'."
fi
if ! chmod u+rw "${HISTFILE}" &>/dev/null; then
  ${ASH_LOG_BIN} -a "Failed to make shell history file readable and writeable."
fi
